// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile-ada-lab/BoldCardsLayout.tsx": () => import("../components/mockups/mobile-ada-lab/BoldCardsLayout.tsx"),
  "./components/mockups/mobile-ada-lab/GlassmorphismLayout.tsx": () => import("../components/mockups/mobile-ada-lab/GlassmorphismLayout.tsx"),
  "./components/mockups/mobile-ada-lab/NeonGamerLayout.tsx": () => import("../components/mockups/mobile-ada-lab/NeonGamerLayout.tsx")
};
